modLoader="javafml"
loaderVersion="[40,)"
license="Public Domain"
[[mods]]
modId="nopotionicons"
version="${file.jarVersion}"
displayName="No Potion Icons"
logoFile="logo.png"
authors="aaronhowser1"
description='Removes potion effect icons from the HUD'
displayTest="IGNORE_ALL_VERSION"
[[dependencies.nopotionicons]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"
# Here's another dependency
[[dependencies.nopotionicons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"